### ISSUE TITLE
Petty Tartaric Gem + Demonic Will Crash

### ISSUE THREAD

**Issue by BluefoxKitsune** [WayofTime/BloodMagic#1068]
#### Issue Description:
Game crashes after picking up Demonic Will with a Petty Tartaric Gem in inventory.
Game also crashes on loading the save that intially crashed with this error.

#### What happens:
Crash on charging Tartaric Gem with picked up Will.

#### What you expected to happen:
Will being absorbed by Tartaric Gem.

#### Steps to reproduce:
1. Have Tartaric Gem
2. Pick up Will from the ground
3. Crash

[crash-2017-02-26_18.06.38-server.txt](https://github.com/WayofTime/BloodMagic/files/802152/crash-2017-02-26_18.06.38-server.txt)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.4-73
- Minecraft: 1.11.2
- Forge: 13.20.0.2237

**Comment by TehNut** [comment]
Already fixed with 5475549c186ea421e6f38814c0deef057150e300. Need to fix a couple things before I push a release.

**Comment by Gayanfalor** [comment]
Hi there i just updated to the blood magic 1.11.2-2.1.5-74, i still getting the crash when i pick up a demon will on the ground, i dont know if its coming because the gem i'm using was created with the older version, and i have not tested with a new one created in 74.

Tell me if i can help

**Comment by tommyTT** [comment]
This also happens for me, unfortunately I'm unable to reproduce it in a test world with only BloodMagic installed. Looking into the code I found that WayofTime.bloodmagic.item.soul.ItemSoulGem.fillDemonWillGem() line 183 returns null instead of the empty item stack which should cause the crash.

**Comment by WayofTime** [comment]
The line he is linking to is this, for quick reference: https://github.com/WayofTime/BloodMagic/blob/1.11/src/main/java/WayofTime/bloodmagic/item/soul/ItemSoulGem.java#L183
And yeah, that would cause an NPE. At the very least, it needs to be addressed.
