### ISSUE TITLE
[1.12.2] Error creating shader

### ISSUE THREAD

**Issue by C0rn3j** [WayofTime/BloodMagic#1325]
Log: https://haste.rys.pw/raw/fadosanela

Files:
forge-1.12.2-14.23.3.2702
jei_1.12.2-4.9.1.187.jar
Guide-API-1.12-2.1.5-60.jar
BloodMagic-1.12.2-2.2.12-97.jar

Game runs but I imagine some graphics are broken.

EDIT: It may or may not be relevant that I'm running 2400G CPU (APU) and mesa-git from AUR (Arch Linux)

**Comment by C0rn3j** [comment]
Still an issue with current forge/mod versions, now on RX 580 using AMDGPU and stable mesa/kernel from Arch repos.

**Comment by keraldi** [comment]
Update.
What is this even?
Please add an extensive description with the issue you are facing (since it's a graphic issue, you might also add screenshots or so).

**Comment by C0rn3j** [comment]
Am not sure what exactly breaks thanks to it but that error is in the logs.

**Comment by keraldi** [comment]
Is it resolved in a recent version? Missing textures usually point to a corrupted download (textures are not missing for me).

You "imagine" graphics are broken because of the error but you haven't seen anything?

The pillars are not implemented and therefore not accessible during normal play.

That's why the issue template is there.
The log says what happened but the user is needed to know how it got there.

**Comment by Johni0702** [comment]
Still happening on 1.12.2-2.4.1-103.
I'm not familiar enough to know of the top of my head what BloodMagic uses those shaders for but the stacktrace and error message in the log looks more than clear to me.

Also running some Mesa variant (18.2.8 from the Debian repos, possibly slightly outdated) on amdgpu but it also happens with the software renderer and based on the error message it's really just some invalid GLSL, shouldn't be too difficult to fix.

**Comment by keraldi** [comment]
I've never worked with that but I'm taking a look at it right now, I'll see if I can come up with a solution in the next few hours. If not, it'll have to wait until after my exams.

**Comment by Johni0702** [comment]
@Iorce I've just made PR which fixes it. See #1624
