### ISSUE TITLE
Soft Coating deletes inventories of items picked up

### ISSUE THREAD

**Issue by TaurusVersant** [WayofTime/BloodMagic#2132]
Blood Magic: 3.3.3-45
Modpack: Reclamation 2.2.0

When I use a tool enchanted with Silk Touch to pick up items that contain inventories such as: a Sophisticated Storage chest wrapped with packing tape or a Source Jar from Ars Nouveau containing Source, the item is picked up containing its current inventory. If I placed the chest down again, it still has the items inside. When I place the Source Jar down, it still has its level of source.

If the tool instead has a Soft Coating applied to it, the contents of the items are deleted. If I break and then place a Sophisticated Storage/packing tape chest down, it's empty. if I place a Source Jar down that I broke with a tool that has Soft Coating, it's empty.

Expected behaviour: inventories should be preserved in such items when broken with an appropriate tool that the soft coating is applied to.

**Comment by stellanera98** [comment]
Already fixed in 3.3.4 BM. Update to reclamation 2.3 once it shows up to get the new version of BM in the pack

**Comment by TaurusVersant** [comment]
I updated to 2.3.0 of Reclamation, which includes Blood Magic 3.3.5-47, and the issue still persists.

**Comment by 305pence** [comment]
I would like to add that my tinker's construct tank had it's contents erased when i broke it with a silk touch anointed tool in Blood Magic 3.3.5-47

**Comment by stellanera98** [comment]
just tested it myself and can confirm its not working, not even with just BM + reqs on a shulker box, which I *swear* worked when I made the fix, and wrince would have tested it as well after that, so not sure why its not working now

**Comment by Saereth** [comment]
Looking at the code, the modifier tries to re-fetch the block entity from the world position:

`BlockEntity be = context.getLevel().getBlockEntity(pos);`

But by the time the loot modifier runs, the block may already be removed. It should likely instead use the existing context parameter: `BlockEntity be = context.getParamOrNull(LootContextParams.BLOCK_ENTITY);`

Sound about right? Happy to pr this

**Comment by stellanera98** [comment]
Tried that as well but to no avail. I think we need to modify the tool used for breaking in whichever event is appropriate

**Comment by Saereth** [comment]
yeah, I dont think the loot modifier can fix this because It runs too late in the process and Regenerating loot through LootTable.getRandomItems() doesn't re-run the special inventory-copying logic that blocks like ShulkerBox have in their playerWillDestroy or getDrops methods. 

Could do some jank adhoc application of silk touch to the item then remove after the break with some kind of tracking few edge cases here which could be annoying.... not sure I like that but the alternative is probably a mixin that can be used to intercept the tool check during block breaking and pretend Silk Touch is present when the anointment is active

**Comment by stellanera98** [comment]
Potentially stupid question, but what if we set the block and be back and then have a fake player with an appropriately modified tool "mine" it? or perhaps even the real player if thats possible?

Another idea would be to listen to the same event the claims protection does, and have it use the proper tool instead (if that can be modified there, if not I guess cancel and redo the breaking with a fake player there)

Not sure where you'd put the mixin and if it would still work with blocks that override the mixin'd method. (Also if it can be avoided we shouldnt use a mixin)
