### ISSUE TITLE
[1.10.2] No damage being done to mobs

### ISSUE THREAD

**Issue by Hastling** [WayofTime/BloodMagic#954]
#### Issue Description:

No damage is done to any mobs with both ranged and melee weapons, but for only select few players regardless if they have OP or not. Less than 12 hours ago this was not the case, removing blood magic solves the issue, additionally deleting player data did not resolve the issue.
http://pastebin.com/7CxLvqxR
#### What happens:

No damage is done to the mob with both ranged and melee weapons, vanilla or otherwise.
#### What you expected to happen:

Damage to occur.
#### Steps to reproduce:
1. Find a Mob
2. Attack the Mob 
3. Cry
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.1.0-65
- Minecraft: 1.10.2
- Forge: 2106

**Comment by TehNut** [comment]
What are the players wearing? The Living Armor check is reporting a null ItemStack

**Comment by Hastling** [comment]
They are wareing nothing. They had cyberware implants but removed them and used their fist.

**Comment by WayofTime** [comment]
I thought this was fixed in -65, looking at the changelog.

**Comment by ViesisGaming** [comment]
I had this happen to me, went as far as to completely delete my minecraft folder, redownload forge - 2016, and used known good copies of the config/mod and am still unable to damage anything.

**Comment by WayofTime** [comment]
Is this still on -65? Guess I'll have to release -66 sooner rather than later.

**Comment by Hastling** [comment]
There was a client server mismatch in versions (my bad) we've update the server to -65. That being said, looking forward to -66 whenever it comes.

**Comment by WayofTime** [comment]
Haha, it's all good~
